/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DispenseRouteImport } from './routes/dispense'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicIotWithdrawRouteImport } from './routes/api/public/iot/withdraw'
import { Route as ApiPublicIotDepositRouteImport } from './routes/api/public/iot/deposit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DispenseRoute = DispenseRouteImport.update({
  id: '/dispense',
  path: '/dispense',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIotWithdrawRoute = ApiPublicIotWithdrawRouteImport.update({
  id: '/api/public/iot/withdraw',
  path: '/api/public/iot/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIotDepositRoute = ApiPublicIotDepositRouteImport.update({
  id: '/api/public/iot/deposit',
  path: '/api/public/iot/deposit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dispense': typeof DispenseRoute
  '/signup': typeof SignupRoute
  '/api/public/iot/deposit': typeof ApiPublicIotDepositRoute
  '/api/public/iot/withdraw': typeof ApiPublicIotWithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dispense': typeof DispenseRoute
  '/signup': typeof SignupRoute
  '/api/public/iot/deposit': typeof ApiPublicIotDepositRoute
  '/api/public/iot/withdraw': typeof ApiPublicIotWithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dispense': typeof DispenseRoute
  '/signup': typeof SignupRoute
  '/api/public/iot/deposit': typeof ApiPublicIotDepositRoute
  '/api/public/iot/withdraw': typeof ApiPublicIotWithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dispense'
    | '/signup'
    | '/api/public/iot/deposit'
    | '/api/public/iot/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dispense'
    | '/signup'
    | '/api/public/iot/deposit'
    | '/api/public/iot/withdraw'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dispense'
    | '/signup'
    | '/api/public/iot/deposit'
    | '/api/public/iot/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DispenseRoute: typeof DispenseRoute
  SignupRoute: typeof SignupRoute
  ApiPublicIotDepositRoute: typeof ApiPublicIotDepositRoute
  ApiPublicIotWithdrawRoute: typeof ApiPublicIotWithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispense': {
      id: '/dispense'
      path: '/dispense'
      fullPath: '/dispense'
      preLoaderRoute: typeof DispenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iot/withdraw': {
      id: '/api/public/iot/withdraw'
      path: '/api/public/iot/withdraw'
      fullPath: '/api/public/iot/withdraw'
      preLoaderRoute: typeof ApiPublicIotWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iot/deposit': {
      id: '/api/public/iot/deposit'
      path: '/api/public/iot/deposit'
      fullPath: '/api/public/iot/deposit'
      preLoaderRoute: typeof ApiPublicIotDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DispenseRoute: DispenseRoute,
  SignupRoute: SignupRoute,
  ApiPublicIotDepositRoute: ApiPublicIotDepositRoute,
  ApiPublicIotWithdrawRoute: ApiPublicIotWithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
